version = '1'

[[sync_targets]]
provider = 'github'
remote_url = 'https://github.com/ihsanmokhlisse/copygit.git'
enabled = true

[[sync_targets]]
provider = 'gitlab'
remote_url = 'https://gitlab.com/ihsanmokhlisse/copygit.git'
enabled = true
